name: 'Github Linter'
description: 'This action checks the github workflow files.'
branding:
  icon: 'alert-circle'
  color: 'gray-dark'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - run: echo "::add-matcher::.github/actionlint-matcher.json"
    - name: Run linters
      uses: docker://rhysd/actionlint:1.7.0
      with:
        args: -color -shellcheck= -pyflakes=